let tarCards = [
  {
    id: 0,
    name: "The Fool",
    number: 0,
    text:
      "Folly, mania, extravagance, intoxication, delirium, frenzy. Reversed: Negligence, absence, distribution, carelessness, apathy, nullity, vanity",
    photo: "./img/major00.jpg",
  },
  {
    id: 1,
    name: "The Magician",
    number: 1,
    text:
      "Skill, diplomacy, address, subtlety, pain, loss, disaster, snares of enemies; self-confidence, will; the Querent, if male. Reversed: Physician, mental disease, disgrace, disquiet.",
    photo: "./img/major01.jpg",
  },
  {
    id: 2,
    name: "The High Priestess",
    number: 2,
    text:
      "Secrets, mystery, the future as yet unrevealed; the woman who interests the Querent, if male; the Querent herself, if female; silence, tenacity; mystery, wisdom, science. Reversed: Passion, moral or physical ardor, conceit, surface knowledge.",
    photo: "./img/major02.jpg",
  },
  {
    id: 3,
    name: "The Empress",
    number: 3,
    text: "You will have luck and love",
    photo: "./img/major03.jpg",
  },

  {
    id: 4,
    name: "The Emperor",
    number: 4,
    text: "You will have luck and love",
    photo: "./img/major04.jpg",
  },
  {
    id: 5,
    name: "The Hierophant",
    number: 5,
    text: "You will have luck and love",
    photo: "./img/major05.jpg",
  },
  {
    id: 6,
    name: "The Lovers",
    number: 6,
    text: "You will have luck and love",
    photo: "./img/major06.jpg",
  },
  {
    id: 7,
    name: "The Chariot",
    number: 7,
    text: "You will have luck and love",
    photo: "./img/major07.jpg",
  },
  {
    id: 8,
    name: "Justice",
    number: 8,
    text: "You will have luck and love",
    photo: "./img/major08.jpg",
  },
  {
    id: 9,
    name: "The Hermit",
    number: 9,
    text: "You will have luck and love",
    photo: "./img/major09.jpg",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    number: 10,
    text: "You will have luck and love",
    photo: "./img/major10.jpg",
  },
  {
    id: 11,
    name: "Strength",
    number: 11,
    text: "You will have luck and love",
    photo: "./img/major11.jpg",
  },
  {
    id: 12,
    name: "The Hanged Man",
    number: 12,
    text: "You will have luck and love",
    photo: "./img/major12.jpg",
  },
  {
    id: 13,
    name: "Death",
    number: 13,
    text: "You will have luck and love",
    photo: "./img/major13.jpg",
  },
  {
    id: 14,
    name: "Temperance",
    number: 14,
    text: "You will have luck and love",
    photo: "./img/major14.jpg",
  },
  {
    id: 15,
    name: "The Devil",
    number: 15,
    text: "You will have luck and love",
    photo: "./img/major15.jpg",
  },
  {
    id: 16,
    name: "The Tower",
    number: 16,
    text: "You will have luck and love",
    photo: "./img/major16.jpg",
  },
  {
    id: 17,
    name: "The Star",
    number: 17,
    text: "You will have luck and love",
    photo: "./img/major17.jpg",
  },
  {
    id: 18,
    name: "The Moon",
    number: 18,
    text: "You will have luck and love",
    photo: "./img/major18.jpg",
  },
  {
    id: 19,
    name: "The Sun",
    number: 19,
    text: "You will have luck and love",
    photo: "./img/major19.jpg",
  },
  {
    id: 20,
    name: "Judgement",
    number: 20,
    text: "You will have luck and love",
    photo: "./img/major20.jpg",
  },
  {
    id: 21,
    name: "The World",
    number: 21,
    text: "You will have luck and love",
    photo: "./img/major21.jpg",
  },
];

let data = JSON.stringify(tarCards);
export { data };
