let tarCards = [
  {
    id: 0,
    name: "The Fool",
    number: 0,
    text: "(fool) you will live happy forever and ever",
    photo: "./img/major00.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 1,
    name: "The Magician",
    number: 1,
    text: "(Magicien) you will have good news very soon",
    photo: "./img/major01.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 2,
    name: "The High Priestess",
    number: 2,
    text: " Priestess you will have good news very soon",
    photo: "./img/major02.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 3,
    name: "The Empress",
    number: 3,
    text: "Empress you will have bad news very soon",
    photo: "./img/major03.jpg",
    backCard: "./img/backCard.jpg",
  },

  {
    id: 4,
    name: "The Emperor",
    number: 4,
    text: "Emperor you will have to take an important decision",
    photo: "./img/major04.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 5,
    name: "The Hierophant",
    number: 5,
    text: "Hierophant you will have good news very soon",
    photo: "./img/major05.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 6,
    name: "The Lovers",
    number: 6,
    text: "Lovers you will have good news very soon",
    photo: "./img/major06.jpg",
    backCard: "./img/backCard.jpg",
  },
  {
    id: 7,
    name: "The Chariot",
    number: 7,
    text: "Chariot you will have good news very soon",
    photo: "./img/major07.jpg",
    backCard: "./img/backCard.jpg",

  }
  // {
  //   id: 8,
  //   name: "Justice",
  //   attribute: 8,
  //   text: "Justice text",
  //   photo: "./img/major08.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 9,
  //   name: "The Hermit",
  //   attribute: 9,
  //   text: "Hermit text",
  //   photo: "./img/major09.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 10,
  //   name: "Wheel of Fortune",
  //   attribute: 10,
  //   text: "Fortune text",
  //   photo: "./img/major10.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 11,
  //   name: "Strength",
  //   attribute: 11,
  //   text: "Strength text",
  //   photo: "./img/major11.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 12,
  //   name: "The Hanged Man",
  //   attribute: 12,
  //   text: "Hanged text",
  //   photo: "./img/major12.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 13,
  //   name: "Death",
  //   attribute: 13,
  //   text: "Death text",
  //   photo: "./img/major13.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 14,
  //   name: "Temperance",
  //   attribute: 14,
  //   text: "Temperance text",
  //   photo: "./img/major14.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 15,
  //   name: "The Devil",
  //   attribute: 15,
  //   text: "Devil text",
  //   photo: "./img/major15.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 16,
  //   name: "The Tower",
  //   attribute: 16,
  //   text: "Tower text",
  //   photo: "./img/major16.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 17,
  //   name: "The Star",
  //   attribute: 17,
  //   text: "Star text",
  //   photo: "./img/major17.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 18,
  //   name: "The Moon",
  //   attribute: 18,
  //   text: "Moon text",
  //   photo: "./img/major18.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 19,
  //   name: "The Sun",
  //   attribute: 19,
  //   text: "Sun text",
  //   photo: "./img/major19.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 20,
  //   name: "Judgement",
  //   attribute: 20,
  //   text: "Judgement text",
  //   photo: "./img/major20.jpg",
  //   backCard: "./img/backCard.jpg",
  // },
  // {
  //   id: 21,
  //   name: "The World",
  //   attribute: 21,
  //   text: "World text",
  //   photo: "./img/major21.jpg",
  //   backCard: "./img/backCard.jpg",
  // },

];

let data = JSON.stringify(tarCards);
export { data };
